version: '3'
services:
  app:
    image: hellmutschuster/webacademy:latest
    container_name: webacademydemo
    restart: always
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
